MERGE (doc1:Document {name: 'Product Format Compatibility with COTS package', format: 'PDF', size_MB: 0.796, url: 'https://mosdac.gov.in/docs/INSAT3D_COTS.pdf'})
MERGE (doc2:Document {name: 'ATBD Document', format: 'PDF', size_MB: 9.8, url: 'https://mosdac.gov.in/docs/INSAT_3D_ATBD_MAY_2015.pdf'})
MERGE (doc3:Document {name: 'Revised ATBD Document for SST', format: 'PDF', size_MB: 1.4, url: 'https://mosdac.gov.in/docs/ATBD_INSAT-3D_SST_REV_V1.1.pdf'})
MERGE (doc4:Document {name: 'Incremental ATBD Document', format: 'PDF', size_MB: 5.2, url: 'https://mosdac.gov.in/docs/Incremental-ATBD-12Feb2020.pdf'})
MERGE (doc5:Document {name: 'Format Document', format: 'PDF', size_MB: 0.903, url: 'https://mosdac.gov.in/docs/INSAT3D_Products.pdf'})
MERGE (doc6:Document {name: 'Product Catalogue', format: 'PDF', size_MB: 0.229, url: 'https://mosdac.gov.in/docs/V1_INSAT3D_ProductTypes%20and%20ProcessingLevel.pdf'})
MERGE (doc7:Document {name: 'INSAT Product Version Information', format: 'PDF', size_MB: 1.61, url: 'https://mosdac.gov.in/docs/INSAT_Product_Version_information_V01.pdf'})
MERGE (doc8:Document {name: 'ATBD_HEM_rain_revised', format: 'PDF', size_MB: 2.14, url: 'https://mosdac.gov.in/docs/HEM_rain-revised-atbd.pdf'})
MERGE (doc9:Document {name: 'Revised ATBD for AOD', format: 'PDF', size_MB: 0.296, url: 'https://mosdac.gov.in/docs/INSAT_AOD_ATBD_revised.doc.pdf'})

MERGE (s:Satellite {name: 'INSAT-3DR'})
MERGE (s)-[:HAS_REFERENCE]->(doc1)
MERGE (s)-[:HAS_REFERENCE]->(doc2)
MERGE (s)-[:HAS_REFERENCE]->(doc3)
MERGE (s)-[:HAS_REFERENCE]->(doc4)
MERGE (s)-[:HAS_REFERENCE]->(doc5)
MERGE (s)-[:HAS_REFERENCE]->(doc6)
MERGE (s)-[:HAS_REFERENCE]->(doc7)
MERGE (s)-[:HAS_REFERENCE]->(doc8)
MERGE (s)-[:HAS_REFERENCE]->(doc9);