MERGE (s:Satellite {name: 'Megha-Tropiques'})
MERGE (madras:Payload {name: 'MADRAS', type: 'Imaging Radiometer'})
MERGE (saphir:Payload {name: 'SAPHIR', type: 'Humidity Sounder'})
MERGE (scarab:Payload {name: 'ScaRaB', type: 'Radiation Measurement Instrument'})
MERGE (rosa:Payload {name: 'ROSA', type: 'Radio Occultation Sensor'})

MERGE (madras)-[:DEVELOPED_BY]->(org1:Organization {name: 'CNES'})
MERGE (madras)-[:DEVELOPED_BY]->(org2:Organization {name: 'ISRO'})
MERGE (saphir)-[:DEVELOPED_BY]->(org1)
MERGE (scarab)-[:DEVELOPED_BY]->(org1)
MERGE (rosa)-[:PROCURED_FROM]->(org3:Organization {name: 'Italian Space Agency (ASI)'})

MERGE (madras)-[:HAS_CHANNEL]->(m1:Channel {name: 'M1', frequency_ghz: 18.7, pol: 'H+V', ne_dT: 0.5, spatial_resolution_km: 40})
MERGE (madras)-[:HAS_CHANNEL]->(m2:Channel {name: 'M2', frequency_ghz: 23.8, pol: 'V', ne_dT: 0.5, spatial_resolution_km: 40})
MERGE (madras)-[:HAS_CHANNEL]->(m3:Channel {name: 'M3', frequency_ghz: 36.5, pol: 'H+V', ne_dT: 0.5, spatial_resolution_km: 40})
MERGE (madras)-[:HAS_CHANNEL]->(m4:Channel {name: 'M4', frequency_ghz: 89, pol: 'H+V', ne_dT: 1.0, spatial_resolution_km: 10})
MERGE (madras)-[:HAS_CHANNEL]->(m5:Channel {name: 'M5', frequency_ghz: 157, pol: 'H+V', ne_dT: 1.0, spatial_resolution_km: 6})

MERGE (saphir)-[:HAS_CHANNEL]->(s1:Channel {name: 'S1', centre_frequency_ghz: 183.31, max_passband_mhz: 200, sensitivity: '<2 (TBC)', absolute_calibration: '± 1', pol: 'H'})
MERGE (saphir)-[:HAS_CHANNEL]->(s2:Channel {name: 'S2', centre_frequency_ghz: 183.31, max_passband_mhz: 350, sensitivity: '<2 (TBC)', absolute_calibration: '± 1', pol: 'H'})
MERGE (saphir)-[:HAS_CHANNEL]->(s3:Channel {name: 'S3', centre_frequency_ghz: 183.31, max_passband_mhz: 500, sensitivity: '<2 (TBC)', absolute_calibration: '± 1', pol: 'H'})
MERGE (saphir)-[:HAS_CHANNEL]->(s4:Channel {name: 'S4', centre_frequency_ghz: 183.31, max_passband_mhz: 700, sensitivity: '<2 (TBC)', absolute_calibration: '± 1', pol: 'H'})
MERGE (saphir)-[:HAS_CHANNEL]->(s5:Channel {name: 'S5', centre_frequency_ghz: 183.31, max_passband_mhz: 1200, sensitivity: '<2 (TBC)', absolute_calibration: '± 1', pol: 'H'})
MERGE (saphir)-[:HAS_CHANNEL]->(s6:Channel {name: 'S6', centre_frequency_ghz: 183.31, max_passband_mhz: 2000, sensitivity: '<2 (TBC)', absolute_calibration: '± 1', pol: 'H'})

MERGE (scarab)-[:HAS_CHANNEL]->(sc1:Channel {name: 'Sc1-Visible', wavelength: '0.5 to 0.7 µm', signal_dynamics: '120 W.m2.sr.-1', noise: '< 1 W.m2.sr.-1'})
MERGE (scarab)-[:HAS_CHANNEL]->(sc2:Channel {name: 'Sc2-Solar', wavelength: '0.2 to 4.0 µm', signal_dynamics: '425 W.m2.sr.-1', noise: '< 0.5 W.m2.sr.-1'})
MERGE (scarab)-[:HAS_CHANNEL]->(sc3:Channel {name: 'Sc3-Total', wavelength: '0.2 to 100 µm', signal_dynamics: '500 W.m2.sr.-1', noise: '< 0.5 W.m2.sr.-1'})
MERGE (scarab)-[:HAS_CHANNEL]->(sc4:Channel {name: 'Sc4-IR Window', wavelength: '10.5 to 12.5 µm', signal_dynamics: '30 W.m2.sr.-1', noise: '< 0.5 W.m2.sr.-1'})

MERGE (rosa)-[:HAS_PARAMETER]->(param1:Parameter {name: 'water vapour', type: 'Atmospheric'})
MERGE (rosa)-[:HAS_PARAMETER]->(param2:Parameter {name: 'temperature profiles', type: 'Atmospheric'})
MERGE (rosa)-[:HAS_SPECIFICATION]->(spec1:Specification {name: 'Frequency', value: 'L1 1.56 to 1.59 GHz; L2 1.212 to 1.242 GHz'})
MERGE (rosa)-[:HAS_SPECIFICATION]->(spec2:Specification {name: 'GPS code used', value: 'C/A and P Code'})
MERGE (rosa)-[:HAS_SPECIFICATION]->(spec3:Specification {name: 'Horizontal Resolution', value: '0.3 km (Low Troposphere); 1-3 km (High Troposphere)'})
MERGE (rosa)-[:HAS_SPECIFICATION]->(spec4:Specification {name: 'Vertical Resolution', value: '<1 K Temperature; 10% or 0.2g/Kg Humidity'})